# Generated by Django 5.0.1 on 2024-02-04 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaria_name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.IntegerField(blank=True, default=0)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')])),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('pizzaria_image', models.ImageField(blank=True, default='pizzariaImages / pizzarialogo.png', upload_to='pizzariaImages')),
                ('email', models.EmailField(blank=True, max_length=400)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
