# Generated by Django 5.0.1 on 2024-02-05 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_pizzaria_pizzaria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaria',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')]),
        ),
    ]
