# Generated by Django 5.0.1 on 2024-02-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_pizzaria_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaria',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
