# Generated by Django 5.0.1 on 2024-02-05 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_pizzaria_phone_pizzaria_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaria',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\0?\\d{9,10}$')]),
        ),
    ]
